<a href="https://colab.research.google.com/github/hyeriong/Data_Analysis/blob/main/query().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# query()

In [10]:
# 데이터 불러오기
from google.colab import files
uploaded = files.upload()

Saving wine.csv to wine (1).csv

In [11]:
import io
import pandas as pd

In [12]:
wine = pd.read_csv(io.BytesIO(uploaded['wine.csv']))

In [13]:
# 데이터 확인
wine.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,red,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,red,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,red,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,red,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,red,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [14]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6497 non-null   object
 1   fixed acidity         6497 non-null   float64
 2   volatile acidity      6497 non-null   float64
 3   citric acid           6497 non-null   float64
 4   residual sugar        6497 non-null   float64
 5   chlorides             6497 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6497 non-null   float64
 10  sulphates             6497 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB

In [17]:
# 컬럼명 공백 제거
wine.columns = wine.columns.str.replace(' ', '_')

In [18]:
wine.columns

Index(['type', 'fixed_acidity', 'volatile_acidity', 'citric_acid',
       'residual_sugar', 'chlorides', 'free_sulfur_dioxide',
       'total_sulfur_dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

컬럼명의 의미 <br>
- fixed acidity : 고정산
- volatile acidity : 휘발산
- critric acid : 구연산
- residual sugar : 잔당
- chlorides : 염화물
- free sulfur dioxide : 유리 이산화황
- total sulfur dioxide : 총 이산화황
- density : 밀도
- pH (산성도)
- sulphates : 황산염
- alcohol : 알코올
- quality : 등급

## 특징
- 정제된 데이터에서 특정 조건을 만족하는 결과를 추출하기 위한 함수
- 가독성과 편의성이 뛰어나다는 장점
- 비교연산, in연산, 논리 연산, 외부 변수 및 참조 연산, 인덱스 검색, 문자열 부분 검색 등을 이용해 표현 가능

In [22]:
# 잔당이 2.0 이하인 레드와인 필터링
wine.query('type == "red" and residual_sugar <= 2.0').head()

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,red,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
3,red,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,red,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,red,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,red,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5

In [23]:
# 고정산이 10보다 크고 휘발산이 0.600 이하인 와인
wine.query('fixed_acidity > 10 and volatile_acidity <= 0.600').head()

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
3,red,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
56,red,10.2,0.42,0.57,3.4,0.070,4.0,10.0,0.9971,3.04,0.63,9.6,5
113,red,10.1,0.31,0.44,2.3,0.080,22.0,46.0,0.9988,3.32,0.67,9.7,6
197,red,11.5,0.30,0.60,2.0,0.067,12.0,27.0,0.9981,3.11,0.97,10.1,6
205,red,12.8,0.30,0.74,2.6,0.095,9.0,28.0,0.9994,3.20,0.77,10.8,7

In [29]:
# 5등급인 레드와인
wine.query('type in "red" and quality == 5')[['type', 'quality']].head()

  type  quality
0  red        5
1  red        5
2  red        5
4  red        5
5  red        5

In [31]:
# 외부변수 또는 함수의 참조 연산 이용하기
pH_wanted = 3.12

wine.query('pH == @pH_wanted')[['type', 'pH']].head()

    type    pH
181  red  3.12
280  red  3.12
305  red  3.12
310  red  3.12
340  red  3.12

In [32]:
# 1000번째 행 검색
wine.query('index == 1000')

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
1000,red,7.5,0.43,0.3,2.2,0.062,6.0,12.0,0.99495,3.44,0.72,11.5,7

In [34]:
# wh로 시작하는 타입의 와인 찾기
wine.query('type.str.startswith("wh")').head()

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
1599,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1600,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
1601,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
1602,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
1603,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [35]:
# d로 끝나는 타입의 와인 찾기
wine.query('type.str.endswith("d")').head()

,type,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,red,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,red,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,red,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,red,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,red,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5